# Generated by Django 2.2.6 on 2020-07-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200717_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('rating', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('state_before', models.TextField()),
                ('state_after', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='p_library.Book')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_friend', to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(related_name='borrows', through='p_library.BorrowBook', to='p_library.Friend'),
        ),
    ]
