# Generated by Django 2.2.6 on 2020-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200719_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='borrows', through='p_library.BorrowBook', to='p_library.Friend'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='state_after',
            field=models.TextField(blank=True),
        ),
    ]
