# Generated by Django 2.2.6 on 2020-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200720_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
