# Generated by Django 2.2.6 on 2020-07-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200720_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='borrowbook',
            options={'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
    ]
