# Generated by Django 2.2.6 on 2020-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200725_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
